# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: meimei 0.8.0 ruby lib

Gem::Specification.new do |s|
  s.name = "meimei".freeze
  s.version = "0.8.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["r888888888".freeze]
  s.date = "2018-03-02"
  s.description = "If all you need is a simple infobot and don't need a full RFC1459 implementation.".freeze
  s.email = "r888888888@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "cron.sh",
    "example/Gemfile",
    "example/Gemfile.lock",
    "example/start.rb",
    "lib/meimei.rb",
    "lib/meimei/array_extensions.rb",
    "lib/meimei/client.rb",
    "lib/meimei/exception_dump.rb",
    "lib/meimei/persistent_hash.rb",
    "lib/meimei/server.rb",
    "meimei.gemspec",
    "plugins/an2.rb",
    "plugins/ann.rb",
    "plugins/autoping.rb",
    "plugins/cco.rb",
    "plugins/choose.rb",
    "plugins/courage.rb",
    "plugins/dan.rb",
    "plugins/dg.rb",
    "plugins/domo.rb",
    "plugins/dwiki.rb",
    "plugins/eta.rb",
    "plugins/g.rb",
    "plugins/gc.rb",
    "plugins/godfinger.rb",
    "plugins/hammerhell.rb",
    "plugins/hanase.rb",
    "plugins/hellheaven.rb",
    "plugins/help.rb",
    "plugins/jtime.rb",
    "plugins/nai_ja_nai.rb",
    "plugins/note.rb",
    "plugins/ranking.rb",
    "plugins/reload.rb",
    "plugins/retard.rb",
    "plugins/rs.rb",
    "plugins/s.rb",
    "plugins/shiningfinger.rb",
    "plugins/shuffle.rb",
    "plugins/shrug.rb",
    "plugins/sugei_inaka.rb",
    "plugins/suki_dakara.rb",
    "plugins/ts.rb",
    "plugins/tsundere.rb",
    "plugins/tt.rb",
    "plugins/ttt.rb",
    "plugins/uptime.rb",
    "plugins/wawawa.rb",
    "plugins/weather.rb",
    "plugins/yeeart.rb",
    "test/helper.rb",
    "test/test_meimei.rb"
  ]
  s.homepage = "http://github.com/r888888888/meimei".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.11".freeze
  s.summary = "Minimalistic IRC bot framework".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<rake>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<json>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<pry>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<yahoofinance>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<timezone>.freeze, [">= 0"])
    else
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<rake>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_dependency(%q<nokogiri>.freeze, [">= 0"])
      s.add_dependency(%q<json>.freeze, [">= 0"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
      s.add_dependency(%q<yahoofinance>.freeze, [">= 0"])
      s.add_dependency(%q<timezone>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<rake>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, [">= 0"])
    s.add_dependency(%q<nokogiri>.freeze, [">= 0"])
    s.add_dependency(%q<json>.freeze, [">= 0"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
    s.add_dependency(%q<yahoofinance>.freeze, [">= 0"])
    s.add_dependency(%q<timezone>.freeze, [">= 0"])
  end
end
